### ISSUE TITLE
feat: Hide model names

### ISSUE THREAD

**Issue by notasquid1938** [dezoito/ollama-grid-search#15]
The option to hide model names can help eliminate personal bias especially when comparing different models. Also, is there any plan to use this to make elo comparisons like a locally running personal https://chat.lmsys.org?

**Comment by dezoito** [comment]
I like the idea of allowing model names to be hidden - at least in the immediate results view.

On the ELO comparisons, could you please expand?

How do you see that working in terms of the UI?

Would you track evals based on the the model's name only, or also for the combination of parameters used in each experiment iteration?

**Comment by dezoito** [comment]
@notasquid1938 ,

Thank you for the clarification.

Although I can see some similarities, I agree that it would take considerable effort (especially since we don't have a database layer in place yet), and diverge from what I had in mind when I started the project.

It's an interesting idea and I'd be happy if someone could make a fork and work on it.

**Comment by dezoito** [comment]
> The option to hide model names can help eliminate personal bias especially when comparing different models. 

@notasquid1938 

Added in [v0.5.0](https://github.com/dezoito/ollama-grid-search/releases/tag/v0.5.0)
