### ISSUE TITLE
Styling improvements for prompt display

### ISSUE THREAD

**Issue by calebsheridan** [dezoito/ollama-grid-search#23]
Currently prompts are displayed as text with whitespace preserved in the inference parameters section and experiment dialog. This has a drawback that long prompts do not fit well and push other important content down.

Potential solutions:
- Use collapsible sections to display any text prompts. Truncate prompt content until it is clicked.
- Use titles or uuids to display text prompts (see #20). Allow library to be opened by clicking on the titles so the prompt can be reviewed.

**Comment by dezoito** [comment]
> Use collapsible sections to display any text prompts. Truncate prompt content until it is clicked.

I'm all for this option, @calebsheridan, since the experiments may refer to prompts that have been deleted or updated since they were run.

For context, I see this view as a human readable log (not saying it can't have some sort of interactivity, just that the data displayed should be a "frozen" snapshot of what happened.

**Comment by dezoito** [comment]
> Use collapsible sections to display any text prompts. Truncate prompt content until it is clicked.

Done in v0.5.1
