### ISSUE TITLE
Feat/idea: A/B testesting diff / horizontal layout

### ISSUE THREAD

**Issue by sammcj** [dezoito/ollama-grid-search#40]
It might be nice to be able to:

1. Layout the generated output horiztonally / in a grid. This would make it easier to compare results.
2. Optionally use diff style highlighting to show differences in the output.

Here's a crappy mock I whipped up:

![ogs-ab-diff](https://github.com/user-attachments/assets/1eee331d-6ea2-41dc-a8f2-4ff5773de119)

Just an idea - feel free to close if not desirable.

**Comment by dezoito** [comment]
I like this idea.

Some possible issues to brainstorm (and I am interested in inputs from anyone that likes it as well).

1) Since a user can generate 100s of results in a single experiment, and that might make scrolling horizontally uncomfortable, and cause issues with the diffing, what if we let the user generate the results then select two of them to compare (like when you compare two different products on Amazon)?

2) If we were to display more than two results side by side, should we diff from the first result or from the previous result?

I think diffing the inference parameters is a great idea, BTW!

**Comment by dezoito** [comment]
Diffing requested on  #62
